// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ----- //
// pulse //
// ----- //

#define pulse_wrap_target 0
#define pulse_wrap 5

static const uint16_t pulse_program_instructions[] = {
            //     .wrap_target
    0x98a0, //  0: pull   block           side 1     
    0x6020, //  1: out    x, 32                      
    0x0042, //  2: jmp    x--, 2                     
    0x90a0, //  3: pull   block           side 0     
    0x6020, //  4: out    x, 32                      
    0x0045, //  5: jmp    x--, 5                     
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program pulse_program = {
    .instructions = pulse_program_instructions,
    .length = 6,
    .origin = -1,
};

static inline pio_sm_config pulse_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + pulse_wrap_target, offset + pulse_wrap);
    sm_config_set_sideset(&c, 2, true, false);
    return c;
}

#endif
